services:
  postgres:
    container_name: postgres_email_verification
    image: postgres:17
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data 
volumes:
  pg_data:
